name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y subversion default-mysql-client

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-8.1-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-8.1-

      - name: Install dependencies
        working-directory: plugin-notation-jeux_V4
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run tests
        working-directory: plugin-notation-jeux_V4
        run: composer test

      - name: Run integration tests
        working-directory: plugin-notation-jeux_V4
        env:
          WP_TESTS_DB_NAME: wordpress_test
          WP_TESTS_DB_USER: root
          WP_TESTS_DB_PASSWORD: root
          WP_TESTS_DB_HOST: 127.0.0.1
        run: composer test:integration

      - name: Run coding standards checks
        working-directory: plugin-notation-jeux_V4
        run: composer cs
